language: ruby
rvm:
  - 2.2.2
env:
  - DB=postgresql
cache: bundler

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare

before_script:
  - bundle exec rake db:migrate

before_script:
  - psql -c 'create databse test' -U postgres

cache: bundler

services:
  - postgresql

addons:
  postgresql: "9.4"
