language: ruby
rvm:
  - 2.2.2
env:
  - DB=postgresql
cache: bundler
bundler_args: --jobs=2
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
before_install:
  - bundle exec rake db:migrate
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create databse' -U postgres
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
